### ISSUE TITLE
Event module doesn't work 

### ISSUE THREAD

**Issue by Mariem-Chaabene** [derhansen/sf_event_mgt#1229] opened 2024-04-26 13:39 UTC
In my project after the migration from typo3 v10 to typo3 v12 , the module event doesn't open anymore 
i have typo3 v12.4 and sf_event v^7.4 , but in other projects the module works fine.
![image](https://github.com/derhansen/sf_event_mgt/assets/95541322/99f416b0-8afb-4de0-8bc2-c7697ca714cc)

**Comment by derhansen** [comment] 2024-04-26 13:57
The error message describes the problem and what to do in this case. Make sure, that the TypoScript of the extension is included on root level and that the folder with events is within the same tree structure. If the folder is outside of a a root level tree structure (e.g. shared with different sites), this is problematic, since settings (e.g. notification settings) can not be configured individually per site. 

If the folder is outside of a root level tree structure by intention, make sure to include the extensions TypoScript for the folder as well.

**Comment by Mariem-Chaabene** [comment] 2024-04-26 14:11
Hi derhansen, thanks for your quick response, but  the Typoscript of the extension is already included in root level and the event folder also is within the same tree structure.

**Comment by derhansen** [comment] 2024-04-26 14:20
In general the backend module works as intended. Please check your local TypoScript setup and that it does not remove required `module.tx_sfeventmgt` TypoScript for the backend module.

**Comment by derhansen** [comment] 2024-05-19 11:33
I'm closing this isue, since it is not reproducable and no additional feedback has been provided.

**Closed by derhansen** 2024-05-19 11:33 UTC
