### ISSUE TITLE
Workspace Compatibility

### ISSUE THREAD

**Issue by rkernberger** [derhansen/sf_event_mgt#249] opened 2015-09-28 14:01 UTC
When using the workspace extension, creating a new event in a workspace is not supported.

When creating a new event in a workspace, it doesn't appear in the list view.

BUT: Editing an existing event in a workspace does work without problems. Could you please check this issue.

Thanks

**Comment by derhansen** [comment] 2015-11-07 18:18
I've done several tests with the extension but could not reproduce the problem. I created a new event in a test workspace I created (it's important to create an event with a future date). Next I checked the FE preview and finally I used the backend Workspace Module to publish the new event, which just worked fine.

Could you give me some more details on how I can reproduce the problem.

**Comment by derhansen** [comment] 2015-12-13 10:43
No feedback for over 30 days, closing issue.

**Closed by derhansen** 2015-12-13 10:43 UTC
Labels: bug, Waiting for feedback
