### ISSUE TITLE
[Bug] Payment: Confirmed Mail on Cancel Action

### ISSUE THREAD

**Issue by jackd248** [derhansen/sf_event_mgt#863] opened 2021-03-23 08:53 UTC
### Extension version
**sf_event_mgt:** 4.3.1

### Short problem description
When canceling a payment process I got redirect correctly to the provided cancel view. But a successful e-mail was sent to the user. Do I have to configure manually which e-mal has to be sent according to the workflow? 

### Expected behaviour
Send the _RegistrationCancelled_ e-mail

### Actual behaviour
The _RegistrationConfirmed_ e-mail was sent.

### Server configuration
**TYPO3 version:** 9.5.22
**PHP version:** 7.2.34

**Comment by derhansen** [comment] 2021-03-23 10:02
The `cancelAction` in the `PaymentController` does not send any emails. How exactly do you cancel the payment process? By cancellation the payment from the payment provider or by cancelling the registration using the cancel-link in the registration email?

The `registrationConfirmed` email is always sent when using payment, since this payment redirect action is only called, when the user confirmed the registration.

If you want to send a cancellation email when the user cancels the payment process, you must implement this using the signalSlot in `cancelAction` of the `PaymentController`

**Comment by jackd248** [comment] 2021-03-24 11:00
I cancel the payment while removing the registration within the `renderCancelView`:

```
public function renderCancelView(&$values, &$updateRegistration, &$removeRegistration, $registration, $pObj)
    {
        $updateRegistration = false;
        $removeRegistration = true;

        $view = $this->getStandaloneViewObject('Cancel.html');
        $view->assignMultiple([
            'event' => $registration->getEvent(),
            'settings' => Configuration::getTyposcriptSettings()
        ]);
        $values['html'] = $view->render();
    }
```

Okay, so I have to handle a cancelation notification within the payment workflow by my own, right?

**Comment by derhansen** [comment] 2021-03-24 14:02
Yes, that is correct.

**Comment by derhansen** [comment] 2021-04-04 06:09
Closing issue.

**Closed by derhansen** 2021-04-04 06:09 UTC
Labels: waiting for feedback
