### ISSUE TITLE
[BUG] Validation in Multilanguage not working

### ISSUE THREAD

**Issue by WiesBen** [derhansen/sf_event_mgt#651] opened 2019-05-04 19:41 UTC
### Extension version
4.0.1

### Short problem description
Opening registration form in an additional language crashes validation of default fields firstname, lastname, email even if it is marked with * as required field.

### Steps to reproduce
1. Create Translation of Page registration
2. Switch from default language to other language
3. Press Form submit

### Expected behaviour
Should mark fields firstname, lastname, email as empty. And block submit.

### Actual behaviour
Only phone and date of birth (which is required by typoscript) are marked if left empty. When filling those two fields only, the form is successfully submitted and when trying to open registration page again I get a wrong url and this error appears:

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1298012500: Required argument "registration" is not set for DERHANSEN\SfEventMgt\Controller\EventController->saveRegistration. | TYPO3\CMS\Extbase\Mvc\Controller\Exception\RequiredArgumentMissingException thrown in file /htdocs/typo3_src-9.5.4/typo3/sysext/extbase/Classes/Mvc/Controller/AbstractController.php in line 406. Requested URL: /media/calendar/registration?tx_sfeventmgt_pievent%%5Baction%%5D=saveRegistration&tx_sfeventmgt_pievent%%5Bcontroller%%5D=Event&tx_sfeventmgt_pievent%%5Bevent%%5D=23&cHash=df7d7c5e03e5885f3859837b8d594a52`

### Server configuration
**TYPO3 version:**
9.5.4

**PHP version:**
7.2.17

**Comment by WiesBen** [comment] 2019-05-04 19:48
Found out it has something todo with typoscript settings:
`plugin.tx_sfeventmgt {
  settings {
    registration {
      requiredFields = gender,dateOfBirth,accepttc,phone
    }
  }
}`
Only these fields are checked. If I add it this way, it is working correctly:
`plugin.tx_sfeventmgt {
  settings {
    registration {
      requiredFields = firstname,lastname,email,gender,dateOfBirth,accepttc,phone
    }
  }
}`

**Comment by WiesBen** [comment] 2019-05-04 19:56
Also found out, Uncaught TYPO3 Exception: #1298012500 only occurs when trying to switch language when already submitted invalid form... seems a to be a separate problem.

**Comment by derhansen** [comment] 2019-05-05 06:05
Thanks for your report. The bug occurs, when an event has registration fields and at least one registration is saved. The problem is already existing since version 3.0 and does also occur on TYPO3 8.7

Obviously, the default Extbase Property validation is ignored, when properties are added/modified  in the `initialize*Action()`.

I'm digging into the problem and will find a solution. It may be best, to completely validate everything manually and do not rely on Extbase property validation in this case.

**Comment by derhansen** [comment] 2019-05-05 17:52
Main problem is [this](https://docs.typo3.org/typo3cms/extensions/core/Changelog/9.5/Important-82363-MakeExtBaseTranslationHandlingConsistentWithTyposcript.html) Core change in TYPO3 9.5. It changes the way Extbase fetches translations of records. That change did break the handling of registrations for events with translations in `sf_event_mgt`, because Extbase now respects the language of items for relations (registrations in this case).

I therefore modified the default getter for the property `registration` of an Event, so it always returns registrations saved to default language (see this [commit](https://github.com/derhansen/sf_event_mgt/commit/4ac8a7360228d5ce9ed1fd8ab71e9fda409b7e9c#diff-5f3b123915e68db86874c69985e3413dR713)). This modification results in the reported problem, as Extbase now somehow resets the validation results for the given registration.

In order to mitigate the problem, I reverted the change of the default getters (`registration` and `registrationsWaitlist`) and added custom getters, which respect the new behavior in Extbase introduced in #82363. However, the fix is a breaking change for users of multilanguage websites, who use custom `Detail.html` and `Registration.html` templates. 

In order to show the exact amount of registrations in Fluid templates, the new getter has to be used.

**Required Change:**
`{event.registration->f:count()}` -> `{event.registrations->f:count()}`

The same applies to the `registrationWaitlist` property, which must be changed to `registrationsWaitlist` if used somewhere.

Bugfix is available in this branch https://github.com/derhansen/sf_event_mgt/commit/989475f7d6a94e3a8245f820ea2f7126cb5f1edd

Would be great if you could test, if everything works properly for you now.

**Comment by WiesBen** [comment] 2019-05-05 20:07
Hi @derhansen ,

indeed this branch fixes the problem. I did not understand why (maybe because I learned php and typo3 only in version 4 and below).

I revert now the manual changes and wait for your update over ter. Is this also the reason, why I can not see registered participants when selecting the english plugin in the backend ?

**Comment by derhansen** [comment] 2019-05-06 05:54
@WiesBen Could you explain the other problem "unable to see registered participants for english plugin"? When does this exactly occur?

**Comment by WiesBen** [comment] 2019-05-06 06:42
@derhansen I attached two screenshots, to describe the problem. It is only switching from german to english language in the upper bar.

![image](https://user-images.githubusercontent.com/40687762/57209905-c75faa80-6fda-11e9-9351-18aee8b7b90d.png)

![image](https://user-images.githubusercontent.com/40687762/57209914-ce86b880-6fda-11e9-8692-e3b675263269.png)

**Comment by derhansen** [comment] 2019-05-06 06:53
Thanks. This is not a bug but actually supposed to work this way. TYPO3 before v9.5 saved registrations to default language regardless of the frontend language. With the mentioned Change in v9.5, this changed. As this introduced a lot of problems (e.g. get exact amount of registrations regardless of language and e.g. this bug), I always save registrations to the default language.

**Comment by WiesBen** [comment] 2019-05-06 06:55
Ok Thanks. Then it is ok for me :D

**Comment by derhansen** [comment] 2019-05-19 09:07
Closing issue, fix will be available in the upcoming version 4.1.0

**Closed by derhansen** 2019-05-19 09:07 UTC
Labels: bug
