### ISSUE TITLE
Filter does not work anymore

### ISSUE THREAD

**Issue by anfuet** [derhansen/sf_event_mgt#239] opened 2015-08-31 15:10 UTC
Since the update of the template, where the category links are generated (#232), the filter does not work anymore. 
My code before:
```
<f:for each="{categories}" as="category">
        <f:link.action action="list" controller="Event" arguments="{category: '{category.uid}'}">{category.title}</f:link.action>
    </f:for>
```
My code after:
```
<f:for each="{categories}" as="category">
                                        <f:if condition="{overwriteDemand.category} == {category.uid}">
                                            <f:then>
                                                <f:link.action action="list" controller="Event" arguments="{overwriteDemand:{category: category}}" class="active">{category.title}</f:link.action>
                                            </f:then>
                                            <f:else>
                                                <f:link.action action="list" controller="Event" arguments="{overwriteDemand:{category: category}}">{category.title}</f:link.action>
                                            </f:else>
                                        </f:if>
                                    </f:for>
```

**Comment by derhansen** [comment] 2015-09-01 06:20
That is really strange, since your new code is the same included in the default template. What exactly does not work? Is RealURL activated and if yes, please try to disable RealURL to make sure, the problem is not related to your RealURL configuration.

**Comment by anfuet** [comment] 2015-09-01 07:04
The Problem is related to my RealURL configuration. Without it configuration the filter works. With RealURL configuration the filter shows all event items instead of only the items of the selected category.

**Comment by derhansen** [comment] 2015-09-01 07:14
You could try to use the RealURL Config from the manual https://docs.typo3.org/typo3cms/extensions/sf_event_mgt/Configuration/RealUrl/Index.html

**Comment by anfuet** [comment] 2015-09-01 14:14
It was a version conflict. After updating the extension RealURL and filter work.

**Comment by derhansen** [comment] 2015-09-01 14:17
Great! Thanks for your feedback. I'll close the issue

**Closed by derhansen** 2015-09-01 14:17 UTC
