### ISSUE TITLE
Registering more then one guests gets wrong count of entries in registered list view

### ISSUE THREAD

**Issue by angeloprevitali** [derhansen/sf_event_mgt#378] opened 2016-10-19 10:58 UTC
sf_event_mgt:  v 1.7.0

TYPO3 CMS: 6.2 (also tried in TYPO3 version 7.6 & 8.4 - the same problem), PHP 5.6, Apache Server.

If you register for an event and you add i.e. 3 persons in the pulldown "amountOfRegistrations" in the FE it generates not three (3) but four entries in the BE (1 entry as registered user and 4 entries for additional guests > "parent registration"). So the total would be five (5) instead of four persons registered in the overview. The only way it works correctly is if you register it for one single person.

```
<f:if condition="{event.maxRegistrationsPerUser} > 1">
<div class="event-registration-row">
<label for="amountOfRegistrations"><f:translate key="tx_sfeventmgt_domain_model_registration.amountOfRegistrations" /></label>
<f:form.select id="amountOfRegistrations" property="amountOfRegistrations" options="{e:event.simultaneousRegistrations(event: '{event}')}" />
</div>
</f:if>
```

Can you fix that?

Thanks.

Best regards,
Angelo

**Comment by derhansen** [comment] 2016-10-19 12:45
I just tested this scenario and can not reproduce the issue. What options (in HTML) are given for the `tx_sfeventmgt_pievent[registration][amountOfRegistrations]` field.

**Comment by angeloprevitali** [comment] 2016-10-19 13:06
Here are some screenshots i just did from the actual config.

![screenshot-2016-10-19-15-00-57](https://cloud.githubusercontent.com/assets/17588253/19519713/714c1a6a-960d-11e6-8e9e-7cf9618978c1.png)
![screenshot-2016-10-19-15-02-34](https://cloud.githubusercontent.com/assets/17588253/19519714/715b0a0c-960d-11e6-9286-551a6de7e777.png)
![screenshot-2016-10-19-15-03-49](https://cloud.githubusercontent.com/assets/17588253/19519715/71618a44-960d-11e6-9d52-c5360cc87a6c.png)

I just entered 4 persons and got 5 in the database.

Does it helps you? Any idea?

**Comment by derhansen** [comment] 2016-10-19 13:17
Are you sure the shown registrations belong to the same event?

I did the same as you and it always results in 3 registrations created.

![image](https://cloud.githubusercontent.com/assets/2629896/19520054/0307217e-960f-11e6-9385-3e603a136883.png)

![image](https://cloud.githubusercontent.com/assets/2629896/19520070/15e232b6-960f-11e6-95be-de7dca95169f.png)

When you open the event, does it show 3 or 4 registration in the "Registrations" tab?

**Comment by angeloprevitali** [comment] 2016-10-19 13:31
If you like I can give you an admin access to the demo page i copied for testing puropses.  So you can check this directly. I send you the access on private mail on @gmail address, ok?
By the way: We are using TYPO3 CMS version 6.2.27 and NOT 7.4 as in your printscreen.

**Comment by angeloprevitali** [comment] 2016-10-19 13:37
Your TYPO3 CMS looks like a TYPO3 version 7.4.... What I am talking about is version 6.2.27. Should not make any difference, right?

**Comment by angeloprevitali** [comment] 2016-10-19 14:44
The screenshot of your registration is how it should be :-) 
But it does not work like this in TYPO3 CMS v 6.2.27. I think that could be (the) reason. Any idea?

**Comment by derhansen** [comment] 2016-10-19 17:21
Also works as expected  in TYPO3 6.2

**Comment by derhansen** [comment] 2016-10-19 17:25
![image](https://cloud.githubusercontent.com/assets/2629896/19529839/ceffde34-9631-11e6-84b9-d8ba29a2ca15.png)

Could it be, that you mean the Numbers to the right? (3, 1 and -)

**Comment by angeloprevitali** [comment] 2016-10-19 17:55
Hello
Yeap. I mean exactly the numbers to the right side.

![screenshot-demo3 web-arts ch 2016-10-19 19-37-44](https://cloud.githubusercontent.com/assets/17588253/19530884/ff634ae4-9635-11e6-93a3-84f9449b73a6.png)

**Comment by angeloprevitali** [comment] 2016-10-19 18:00
In other words again: Have a look to the upper printscreen. We got as total 2 items listed in the BE for three (3) persons. So this total of persons in the BE isn't correct.

**Comment by derhansen** [comment] 2016-10-19 18:10
I think that is some kind of misleading.

Actually, only 2 registrations got created (as you can see, the table only shows 2). The column you look at shows the amount of total registrations, if the user created more than one at a time. Since the first registration (the one with the 2) is the main registration, the amount "2" is saved there. For the depending registration (the one below), the amount "1" has no further meaning.

Please open the Event and look in the "Registrations" tab. The amount of registrations matches exactly the amount of registrations created with the form.

Does this exclamation help?

**Comment by angeloprevitali** [comment] 2016-10-19 18:13
I just tested again and found now how to explain it.
The amount of persons is NOT correct in the total.

![12](https://cloud.githubusercontent.com/assets/17588253/19531526/4f41cc28-9638-11e6-95b3-91df77d5ad5d.png)

![13](https://cloud.githubusercontent.com/assets/17588253/19531605/6eaa4482-9638-11e6-9bd4-2d495d00b926.png)

**Comment by derhansen** [comment] 2016-10-19 18:19
Please read my exclamation above :-)

You don't have to sum up those values. Count the amount of registrations in the table and you come up to 10. 

All registrations are managed through the event, so if you open the "Registrations" tab as I suggested, you will see, that there are 10 registrations in total. The summed up value you calculated is not used anywhere and does not represent the total amount of registrations.

The value of the column "Anzahl Anmeldungen (...)" is only important for master registrations (those without a parent!).

**Comment by derhansen** [comment] 2016-10-22 03:30
Closing issue. Feel free to contact me if you have further questions.

**Closed by derhansen** 2016-10-22 03:30 UTC
