### ISSUE TITLE
[TASK] Templates for email notifications always taken from sf_event_mgt

### ISSUE THREAD

**Issue by sascha-schieferdecker** [derhansen/sf_event_mgt#409] opened 2017-04-12 05:20 UTC
### Extension version
1.8.1

### Short problem description
Template path overriding does not work for email notifications

### Steps to reproduce
Following setup:

plugin.tx_sfeventmgt {
    view {
        templateRootPaths {
            1 = EXT:xxx/Resources/Private/ext/sf_event_mgt/Templates
        }
        partialRootPaths {
            1 = EXT:xxx/Resources/Private/ext/sf_event_mgt/Partials
        }
    }
}

does override all templates except the notifications which reside in the folder "Notification":

![image](https://cloud.githubusercontent.com/assets/8793359/24942294/46006cfe-1f50-11e7-859f-efade6bbb473.png)

### Expected behaviour
Templates from the overriden folder should be used

### Actual behaviour
Templates ignored

### Server configuration
**TYPO3 version:**
7.6.16

**PHP version:**
IMHO not relevant

**Comment by derhansen** [comment] 2017-04-12 06:08
I just tested the e-mail template override on a TYPO3 7.6.16 website with the latest version of sf_event_mgt and I can't reproduce the problem.

E-Mail arrives with my overridden template (see screenshot below - template is taken from fileadmin `templateRootPath = fileadmin/templates/events/Templates/` in constants)

![image](https://cloud.githubusercontent.com/assets/2629896/24943342/8154de42-1f56-11e7-8958-de9f6aa21dff.png)

Are you working on a Mac and do you use case insensitive filesystem? If so, please check, that the Folders and Files for notification do have the correct case.

**Comment by sascha-schieferdecker** [comment] 2017-05-14 11:43
Hello, I just had time to look at the issue again. It's the slashes at the end of the path that make the difference. 

If I set EXT:xxx/Resources/Private/ext/sf_event_mgt/Templates the templates are taken from the original location. If set EXT:xxx/Resources/Private/ext/sf_event_mgt/Templates_/_ it works.

Maybe this could be improved in class FluidStandaloneService or in the docs, because this only affects the email templates.

**Comment by derhansen** [comment] 2017-06-27 18:40
Does not work at all in TYPO3 8.7 - maybe a core issue. I'm currently investigating

**Comment by derhansen** [comment] 2017-06-28 09:24
Update: This seems to a issue in TYPO3 8.7 - I already have a solution ready and will provide a working version for TYPO3 7.6 and 8.7 soon

**Comment by derhansen** [comment] 2017-07-02 05:15
Fixed in development version. FluidStandaloneService now checks and adds the missing slash. Also the class has been covered with unit tests.

**Closed by derhansen** 2017-07-02 05:15 UTC
Labels: bug
