### ISSUE TITLE
SQL error when saving a record (TYPO3 8.7, branch development)

### ISSUE THREAD

**Issue by tmotyl** [derhansen/sf_event_mgt#422] opened 2017-04-19 11:03 UTC
### Extension version
2.0-dev, development branch, b5e41e426d445e0b3154ac5fa72c7f2730d8acd1
### Short problem description
I'm getting error:
`SQL error: 'Incorrect integer value: '' for column 'location' at row 1' (tx_sfeventmgt_domain_model_event:NEW58f743228c7b0853916830)`

### Steps to reproduce
1. Go to events module
2. click on the button "create new event"
3. fill "Title" field
4. click save button

### Expected behaviour
Record is saved correctly

### Actual behaviour
Error is thrown, data is not saved

### Server configuration
**TYPO3 version:**
8.7
**PHP version:**
7.0

**Comment by derhansen** [comment] 2017-04-19 11:17
I can't reproduce the problem. Can you check in the install tool, if all DB migrations are done and also clear the cache completely.

**Comment by tmotyl** [comment] 2017-04-19 12:17
Hi,
just double checked the db migrations and cache, done and cleared.
The problem exists if you do not select any organizer and location in the "Relation" tab, despite these relations are not mandatory.

Also if you remove location or organizer in the Relations tab, you will get the same issue.

**Comment by tmotyl** [comment] 2017-04-19 12:35
Similar issue is when editing Registration record and not filling `fe_user`. 
`2: SQL error: 'Incorrect integer value: '' for column 'fe_user' at row 1' (tx_sfeventmgt_domain_model_registration:NEW58f7592653be3886165393)`

**Comment by tmotyl** [comment] 2017-04-19 12:44
the offending query is 
```
 'UPDATE `tx_sfeventmgt_domain_model_event` SET `price` = ?, `location` = ?, `related` = ?, `category` = ?, `tstamp` = ?, `t3ver_stage` = ? WHERE `uid` = ?' 

with params ["0.00", "", "0", "0", 1492605723, 0, 1]

```
Maybe it's a core bug?

**Comment by tmotyl** [comment] 2017-04-19 12:53
if I set `SET SESSION sql_mode=''` in the install tool , then the error is not shown (I mean the red flash message) however saving still don't work.

**Comment by derhansen** [comment] 2017-04-19 15:04
Thanks for your PR. Merged

**Closed by derhansen** 2017-04-19 15:04 UTC
