### ISSUE TITLE
Custome translation as described in manual not working after getting translations 

### ISSUE THREAD

**Issue by angeloprevitali** [derhansen/sf_event_mgt#305] opened 2016-03-22 10:40 UTC
Bough examples shown in manual are only working if there are not getting new trasnaltions in BE getted. 

$GLOBALS['TYPO3_CONF_VARS']['SYS']['locallangXMLOverride']['de']['EXT:sf_event_mgt/Resources/Private/Language/locallang_db.xlf'][] = 'EXT:your_ext/Resources/Private/Language/de.custom_locallang_db.xlf';

$GLOBALS['TYPO3_CONF_VARS']['SYS']['locallangXMLOverride']['de']['EXT:sf_event_mgt/Resources/Private/Language/locallang.xlf'][] = 'EXT:your_ext/Resources/Private/Language/de.custom_locallang.xlf';

**Comment by derhansen** [comment] 2016-12-26 18:26
I tried to reproduce the problem with no success. Overriding language labels works as expected and since this is a TYPO3 core [feature](https://docs.typo3.org/typo3cms/CoreApiReference/6.2/Internationalization/Translation/), I'll close this issue.

If you need any help, feel free to contact me

**Closed by derhansen** 2016-12-26 18:26 UTC
