### ISSUE TITLE
[BUG] Preselect category in list view error

### ISSUE THREAD

**Issue by fabianscholz** [derhansen/sf_event_mgt#433] opened 2017-05-21 11:58 UTC
### Extension version
2.0.0

### Short problem description
If i select one or more categories in a list view, i get the following error:

`#1327065745: Unsupported or non-existing property name "category" used in relation matching. (More information) 
TYPO3\CMS\Extbase\Persistence\Generic\Exception\RepositoryException thrown in file
/html/typo3/typo3_src-8.7.1/typo3/sysext/extbase/Classes/Persistence/Generic/Storage/Typo3DbQueryParser.php in line 371.`

I thinks it's a problem near the function: setCategoryConstraint() but i doesn't find it.
Can you help me? I try to show a list of events from one category.

Thanks!

### Server configuration
**TYPO3 version: 8.7.1**

**PHP version: 7.1.1**

**Comment by derhansen** [comment] 2017-05-21 12:41
I can't reproduce the problem. Tried to add a list plugin on a page, selected a category in the plugin and the frontend shows all events, which are assigned to the category.

Did you upgrade from a previous version of the extension? If yes, make sure you run the extension update script in the extension manager.

Also try a DB compare in the install tool and see, if the field "category" gets added. Check the database table `tx_sfeventmgt_domain_model_event` for existence of the field `category``

Last, you could try to downgrade to PHP 7.0

Please let me know, if anything fixes your problem

**Comment by fabianscholz** [comment] 2017-05-21 16:28
Hi, thanks for the response.
The install ist not a upgrade. It's a fresh install of Typo3 with some flux elements. I try to downgrade the php to PHP 7.0 but it doesn't help. The DB compare runs without errors or corrections. The Table has a field named 'category'. I have upload a trace, i hope you can see more: http://dev.scholz.plus/TYPO3_Exception.html

I have debug the category id that defined in the settings and the `$constraints[] = $query->logicalOr($categoryConstraints);`

I don't know how is the problem ...

**Comment by derhansen** [comment] 2017-05-21 18:13
I still can't reproduce the problem on TYPO3 8.7. 

Is there any extension present, that could override the TCA of the Category column?

**Comment by fabianscholz** [comment] 2017-05-21 18:22
Hmm ... i use following Extensions:

- Gridelements (8.0.0-dev)
- fluidcontent (5.2.0)
- flux (8.2.1)
- vhs (4.2.0)
- sf_event_mgt (2.0.0)
- unroll (2.0.0)

But i don't know which ext will override the TCA.

**Comment by derhansen** [comment] 2017-05-22 06:03
Seems all good to me. Since you wrote it is a fresh TYPO3 8.7 installation, could you provide me the whole site as .tgz, so I can do some local debugging on it?

**Comment by derhansen** [comment] 2017-05-24 05:21
Problem solved by reinstalling extension and DB Compare in install tool

**Comment by derhansen** [comment] 2017-06-19 08:15
I'll reopen this issue, since the problem occurred in a different project of mine. I think I have found the solution and will create a patch very soon.

**Closed** 2017-06-27 13:05 UTC
Labels: bug
