### ISSUE TITLE
Image handling in multi language setup

### ISSUE THREAD

**Issue by paul-keller** [derhansen/sf_event_mgt#540] opened 2018-04-23 15:43 UTC
### Extension version
Version 3.0.1

### Short problem description
I have got different alt and title text for images in the different languages.
In detail view I always get the text of the standard language.
I am even using the extensions faltranslation and repair_translation but nothing helps.
It can't be a general problem, because with extension news it works correctly.

### Steps to reproduce
1. add picture with alt text to seminar
2. translate seminar to second language and fill in different alt text
3. view seminar in frontend in second language. Alt Text of standard language is displayed.

### Expected behaviour
title and alt text should be displayed according to the language shown

### Actual behaviour
Allways standard language is displayed

### Server configuration
**TYPO3 version:**
8.7.2
**PHP version:**
7.0.22

**Comment by schrob3000** [comment] 2018-11-08 15:51
## Same issue with:
sf_event_mgt: 3.0.6
PHP: 7.0.30
TYPO3: 8.7.19

Translation of files does not work.

**Comment by derhansen** [comment] 2018-11-08 18:21
Extbase FAL File Translation is sadly broken in TYPO3 Core since TYPO3 6.2 and up to 8.7 (including that version). See: https://forge.typo3.org/issues/57272

I double checked the issue @paul-keller reported but can't reproduce the problem. 

Event for default language:

![image](https://user-images.githubusercontent.com/2629896/48218631-9a636f80-e38a-11e8-8fdd-70b8a1040b80.png)

Translated event (same image/different alternative and title):

![image](https://user-images.githubusercontent.com/2629896/48218663-acdda900-e38a-11e8-81a5-e44435266c2b.png)

You have to make sure to use the correct translation behavior (see screenshot)

![image](https://user-images.githubusercontent.com/2629896/48218704-c54dc380-e38a-11e8-91bb-39b8a81ef4b3.png)

@schrob3000 

In order to fix translation in TYPO3 8.7, please install this extension https://github.com/froemken/repair_translation

As you can see in the forge issue, there still is some discussion around the problem for TYPO3 8.7 and maybe the fix, that was added in TYPO3 9.5, will be backported to TYPO3 8.7. This may need some help (support/review/sponsoring)

Im closing this issue now and will add a hint in the FAQ section about ext:repair_translation

**Closed by derhansen** 2018-11-08 18:21 UTC
